#!/usr/bin/env bash
# Install, configure, and start the load balancer for beta-scribbles.tech

# Update repositories and install HAProxy
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Load balancer configuration
DOMAIN_NAME='beta-scribbles.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HA_PROXY_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
    balance roundrobin
    server 230996-web-01 54.175.38.249:80 check
    server 230996-web-02 100.25.23.166:80 check
frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

# Ensure ENABLED flag in init file
if ! grep -qE '^ENABLED=[01]$' "$INIT_FILE"; then
    echo 'ENABLED=1' >> "$INIT_FILE"
else
    sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
fi

# Update or append HAProxy configuration in the config file
if grep -qE "$DOMAIN_NAME-backend" "$CONFIG_FILE"; then
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONFIG_FILE"
fi
echo -en "$HA_PROXY_CONFIG" >> "$CONFIG_FILE"

# Restart or start HAProxy service
if pgrep -q haproxy; then
    service haproxy restart
else
    service haproxy start
fi

echo "HAProxy configuration for $DOMAIN_NAME completed."
